name: torch-cu128
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - anyio=4.12.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attr=2.5.2
  - attrs=25.4.0
  - babel=2.17.0
  - backports.zstd=1.2.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask-core=2025.12.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.18
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - entrypoints=0.4
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2025.12.0
  - gdk-pixbuf=2.42.12
  - glib=2.84.0
  - glib-tools=2.84.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=11.0.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagecodecs-lite=2019.12.3
  - imageio=2.37.0
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=7.4.9
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libass=0.17.3
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.10.0
  - libopengl=1.7.0
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=17.7
  - libprotobuf=5.27.5
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - locket=1.0.0
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - mpg123=1.32.9
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - nspr=4.38
  - nss=3.118
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.5.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-opencv=4.10.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - pywavelets=1.9.0
  - pyyaml=6.0.3
  - pyzmq=24.0.1
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.0
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scikit-image=0.20.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlite=3.51.0
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2020.6.3
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.3.0
  - toolz=1.1.0
  - tornado=6.5.3
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.2
  - wayland=1.23.1
  - wayland-protocols=1.46
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - filelock==3.20.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - protobuf==6.33.4
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - sentry-sdk==2.50.0
      - smmap==5.0.2
      - sympy==1.14.0
      - torch==2.9.1+cu128
      - torchaudio==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - triton==3.5.1
      - typing-inspection==0.4.2
      - wandb==0.24.0

